### ISSUE TITLE
Doesn't work as expected

### ISSUE THREAD

**Issue by swanzai** [deniaz/wp-dms#1]
How strange you would release a plugin the day that I need something like this. 
Unfortunately it's not working for me at the moment. 

I have 3 domains, each pointed to the same document root with WP installed in a subdir (example.com running from example.com/wordpress). When I create a new Domain Map Entry, no changes occur. 

Normally I can debug a bit but your code's a bit beyond me. Rest assured I tried from both alternate domains, with and without www, from multiple browsers, no luck. 

[edit] Tried moving the site to the root directory -- now the plugin has an effect, but results in blank pages for domains it should forward from.

**Comment by deniaz** [comment]
Hi swanzai!
First of all, thanks for trying my plugin! I'm sure we'll get it running for you.

Concerning running DMS on a WordPress instance in a subdirectory: this could very well be the reason it doesn't work. I'll give it a shot in a second and I'll see whether this is a problem or not and try fixing it.

I'm a glad there is an effect in the root directory, though. 
In the DMS Options there is an _exit_ - Checkbox. Could you try unchecking this one? And furthermore, what template did you choose for the WordPress Page which is mapped to the domain?

**Comment by swanzai** [comment]
Unchecking the exit checkbox solved the blank page problem issue -- but sunk me a bit deeper in confusion.

The theme that I'm developing on is Thesis -- I tried rolling back to TwentyEleven as well to try and find some consistency -- but depending on what template I selected I'd get various results including a 'no results' blog page with a 'home' page below it (two headers, two content areas, two footers), but more commonly just the 'home' page no matter what page I had selected for that domain to forward to. 

Are things supposed to still be functional if I just leave the page as the default template? Am I supposed to have a copy of the page template in the plugins /template dir? Ideally example.biz displays the full site, example.com displays the full site sans one page in the menu, and example.info shows the full site with the blog page as the front page instead of the 'home' page. This seems doable -- but let me know if this is out of the scope of what I'm supposed to be able to achieve.

Thanks for the help!

[edit] Not that I'm giving up on you -- still have usage scenarios in mind for this guy -- but for this particular job I did find more what I'm looking for in a plugin called MiniMU -- allows similar functionality but a) makes nav links consistent with the 'apparent' domain and b) gives a broader array of variables I can switch up, site name, theme, etc. 

It's not you, it's me. ;)

**Comment by deniaz** [comment]
Good news: I could verify all your reports, so it's definitely me ;) bad news: I'll need a moment to fix this.

If you've already switched to another plugin, good on you, mate ;) But I'd really appreciate if you could test the next release with the fixes (I'll let you know!). It's actually the first plugin I released, which wasn't custom-cut for a client. So you've found some bugs I would've never discovered on my own. I'm glad you reported the bugs!!

Hope you'll have a look at the release in a few hours.

_[edit] I've just pushed some new code to github, the default page templates, etc. should now work! I'll have a look at the subdirectory issue now, and then at your specific requirements._

**Comment by deniaz** [comment]
The plugin page on wordpress.org and the github repo are now uptodate (strangely not the button-text on wp.org though).
There was some hacking from my part, which is now fixed. You should see proper results now with twentyeleven and your Thesis theme (haven't tried it out with Thesis though, but with other themes).

Your case is a bit special.
- example.biz does not need to be mapped with DMS.
- example.com would need a custom page template, which would load a menu without the menu entry you don't require
- example.info in your Thesis theme you'll probably configure a "blog" page or sth, so you should map example.info to that page.

If DMS doesn't fulfill your requirements - fair enough. But I'd really appreciate if you could try out the new version (1.1) and report back, whether it works now as expected or not. Thanks!!

**Comment by swanzai** [comment]
Rock on! Turns out my solution is running Domain Mapping System in parallel with MiniMU, which appears to be working fine. Got it working on the site I was developing yesterday as well as a new site today. Thanks a lot for your help, and the great plugin!

**Comment by deniaz** [comment]
Great to here! Thanks for your feedback and rock on ;)
