### ISSUE TITLE
Readme, link to "Official Website" not working

### ISSUE THREAD

**Issue by neverything** [deniaz/wp-dms#2]
The link in your Readme "Offical Website" points to your site http://www.cheekyowl.com/wp/wp-dms and this one doesn't exist. It's not a big issue, but you should fix it.

Btw. great to see other swiss based WordPress enthusiasts.

**Comment by deniaz** [comment]
Cheers, fixed this with the release of DMS 1.2 today!

I think there are actually quite a few, but you rarely encounter them in the wild ;)
