### ISSUE TITLE
Allow choice between page and blog post as front page

### ISSUE THREAD

**Issue by jas4711** [deniaz/wp-dms#3]
Hi!  Thanks for this plugin, I believe something like it is what I need.  I have a blog on blog.josefsson.org and a regular website on josefsson.org that I'd like to redo in wordpress.  So I'm setting up wordpress on josefsson.org and using DMS to add a blog.josefsson.org sub-site.  Everything works, but I want the blog.josefsson.org address to go straight to the blog and not to a particular page.

I have looked at the "Domain theme" plugin which is similar to DMS, and I noticed that someone had modified it into "New Domain theme" with the added feature that you can make this choice.  Maybe you compare how that is implemented and borrow that approach?

Domain theme: http://wordpress.org/extend/plugins/domain-theme/
New domain theme: http://feisun.org/wordpress/plugins/new-domain-theme/

Thanks,
Simon

**Comment by deniaz** [comment]
Hi Simon

Thanks for the feedback.

Well, I'll look into this as soon as I find time.
I'll let you know how things go!

Regards,
Rob

**Comment by deniaz** [comment]
So, I've looked into it.

Right now, DMS serves another purpose. DMS is written to map domains to pages/posts/whatever.
The thought behind this is to manage a blog/site and multiple single pages in one WordPress instance (e.g. company website + product info pages).

_(New) Domain Theme_ does something else and uses a completely different approach.
I'll think about an easy and intelligent way to implement this feature into DMS. 

Regards,
Rob

**Comment by jas4711** [comment]
Thanks for looking into it.  Meanwhile, I've found it easier to use two wordpress installations instead.
