### ISSUE TITLE
Not all posts in dropdown

### ISSUE THREAD

**Issue by joshlevinson** [deniaz/wp-dms#4]
Only 11 of many of my CPT posts show up in the drop down. Searching for the post types by name doesn't help. All posts have the same author and status.

**Comment by deniaz** [comment]
Hi Josh

Does it show only 11 CPT of many or 11 Posts of many per CPT?

I'll definitely look into this as soon as I find time.

Regards,
Rob

**Comment by deniaz** [comment]
Hi Josh

With this Commit: https://github.com/deniaz/wp-dms/commit/693a029a65039b6a55502b9ebd5dae7c772c676e I've addressed the issue. 

Alternatively, you can just download the current version from wordpress.org/extend/plugins/domain-mapping-system/ .

Regards,
Rob
